import os
import re
import glob
import shutil

# Configuration
INPUT_DIR = "clustered_output"
OUTPUT_DIR = "dist"
CSS_FILE = "style.css"
MAX_FILES = 10
IMAGE_LIST_FILE = "image_list.txt"
IMAGE_SOURCE_DIR = os.path.join(INPUT_DIR, "images")

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <link rel="stylesheet" href="../css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">
</head>
<body>
    <div class="container">
        <header>
            <a href="../index.html" class="back-link">← Back to Dashboard</a>
            <h1>{title}</h1>
            <p class="subtitle">{question_count} Questions</p>
        </header>

        <main>
            {questions_html}
        </main>

        <footer>
            <p>Generated by Agentic AI</p>
        </footer>
    </div>
    <script src="../js/main.js"></script>
</body>
</html>"""

INDEX_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Question Bank Dashboard</title>
    <link rel="stylesheet" href="css/style.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">
</head>
<body>
    <div class="container">
        <header class="dashboard-header">
            <h1>Question Bank Dashboard</h1>
            <p class="subtitle">Select a subject to practice</p>
        </header>

        <div class="grid">
            {links_html}
        </div>
    </div>
</body>
</html>"""

CSS_CONTENT = """/* Reset & Base */
:root {
    --bg-color: #0f172a;
    --card-bg: rgba(30, 41, 59, 0.7);
    --text-primary: #f1f5f9;
    --text-secondary: #94a3b8;
    --accent: #8b5cf6;
    --accent-hover: #7c3aed;
    --border: rgba(148, 163, 184, 0.1);
    --success: #10b981;
    --error: #ef4444;
}

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
    font-family: 'Inter', sans-serif;
    background-color: var(--bg-color);
    color: var(--text-primary);
    line-height: 1.6;
    min-height: 100vh;
    background-image:
        radial-gradient(circle at 10% 20%, rgba(139, 92, 246, 0.1) 0%, transparent 20%),
        radial-gradient(circle at 90% 80%, rgba(16, 185, 129, 0.05) 0%, transparent 20%);
}

.container {
    max-width: 900px;
    margin: 0 auto;
    padding: 2rem;
}

/* Typography */
h1 { font-size: 2.5rem; font-weight: 700; margin-bottom: 0.5rem; letter-spacing: -0.025em; }
.subtitle { color: var(--text-secondary); margin-bottom: 2rem; }
a { text-decoration: none; color: inherit; }

/* Header */
header { margin-bottom: 3rem; text-align: center; }
.dashboard-header { padding: 4rem 0; }
.back-link {
    display: inline-block;
    margin-bottom: 1rem;
    color: var(--accent);
    font-weight: 600;
    transition: transform 0.2s;
}
.back-link:hover { transform: translateX(-5px); }

/* Grid (Dashboard) */
.grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 1.5rem;
}

.card-link {
    display: block;
    background: var(--card-bg);
    padding: 1.5rem;
    border-radius: 1rem;
    border: 1px solid var(--border);
    backdrop-filter: blur(12px);
    transition: transform 0.2s, box-shadow 0.2s, border-color 0.2s;
}

.card-link:hover {
    transform: translateY(-5px);
    box-shadow: 0 10px 30px -10px rgba(0, 0, 0, 0.5);
    border-color: var(--accent);
}

.card-link h2 { font-size: 1.25rem; margin-bottom: 0.5rem; }
.card-link p { font-size: 0.875rem; color: var(--text-secondary); }

/* Question Card */
.question-card {
    background: var(--card-bg);
    border: 1px solid var(--border);
    border-radius: 1rem;
    padding: 2rem;
    margin-bottom: 2rem;
    backdrop-filter: blur(12px);
    overflow: hidden; /* For animations */
}

.q-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 1rem;
    border-bottom: 1px solid var(--border);
    padding-bottom: 1rem;
}

.q-number {
    font-size: 0.875rem;
    color: var(--accent);
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.05em;
}

.q-id { font-size: 0.75rem; color: var(--text-secondary); font-family: monospace; }

.q-text {
    font-size: 1.125rem;
    margin-bottom: 1.5rem;
    font-weight: 500;
    overflow-wrap: break-word; /* FIX: Prevent overflow */
    word-break: break-word;   /* FIX: Force break long words */
}

/* Images */
.q-images {
    margin-bottom: 1.5rem;
    display: flex;
    flex-wrap: wrap;
    gap: 1rem;
}
.q-image {
    max-width: 100%;
    max-height: 300px;
    border-radius: 0.5rem;
    border: 1px solid var(--border);
}

.options-list {
    list-style: none;
    margin-bottom: 2rem;
}

.option-item {
    padding: 1rem 1.25rem;
    margin-bottom: 0.75rem;
    border-radius: 0.75rem;
    background: rgba(255, 255, 255, 0.03);
    border: 1px solid rgba(255, 255, 255, 0.05);
    transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);
    cursor: pointer; /* FIX: Interactivity */
    display: flex;
    align-items: flex-start;
    overflow-wrap: break-word;
    word-break: break-word;
}

.option-item:hover:not(.disabled) {
    background: rgba(255, 255, 255, 0.08);
    transform: translateX(5px);
}

.option-label {
    font-weight: 700;
    margin-right: 1rem;
    color: var(--text-secondary);
    min-width: 1.5rem;
}

/* Interactive States */
.option-item.correct {
    background: rgba(16, 185, 129, 0.2);
    border-color: var(--success);
    color: #fff;
    animation: pop 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);
}

.option-item.correct .option-label { color: var(--success); }

.option-item.wrong {
    background: rgba(239, 68, 68, 0.2);
    border-color: var(--error);
    color: #fff;
    animation: shake 0.4s cubic-bezier(.36,.07,.19,.97) both;
}

.option-item.wrong .option-label { color: var(--error); }

.option-item.disabled {
    cursor: default;
    opacity: 0.7;
}

/* Answer Reveal */
.answer-section {
    border-top: 1px solid var(--border);
    padding-top: 1.5rem;
}

.reveal-btn {
    background: var(--accent);
    color: white;
    border: none;
    padding: 0.75rem 1.5rem;
    border-radius: 0.5rem;
    font-weight: 600;
    cursor: pointer;
    font-family: inherit;
    transition: background 0.2s;
}

.reveal-btn:hover { background: var(--accent-hover); }

.answer-content {
    display: none;
    margin-top: 1.5rem;
    padding: 1rem;
    background: rgba(255, 255, 255, 0.03);
    border-radius: 0.5rem;
    border-left: 3px solid var(--accent);
    animation: fadeIn 0.4s ease;
}

.answer-content.visible { display: block; }

.correct-ans-label {
    color: var(--success);
    font-weight: 700;
    font-size: 1.1rem;
    margin-bottom: 0.5rem;
    display: block;
}

.explanation-text {
    margin-top: 1rem;
    font-size: 1rem;
    color: var(--text-primary);
    line-height: 1.6;
}

.ai-pill {
    display: inline-block;
    font-size: 0.7rem;
    background: linear-gradient(135deg, #6366f1, #a855f7);
    color: white;
    padding: 2px 8px;
    border-radius: 12px;
    margin-bottom: 0.5rem;
    letter-spacing: 0.05em;
    font-weight: 700;
}

/* Animations */
@keyframes fadeIn {
    from { opacity: 0; transform: translateY(10px); }
    to { opacity: 1; transform: translateY(0); }
}

@keyframes pop {
    0% { transform: scale(1); }
    50% { transform: scale(1.02); }
    100% { transform: scale(1); }
}

@keyframes shake {
  10%, 90% { transform: translate3d(-1px, 0, 0); }
  20%, 80% { transform: translate3d(2px, 0, 0); }
  30%, 50%, 70% { transform: translate3d(-4px, 0, 0); }
  40%, 60% { transform: translate3d(4px, 0, 0); }
}
"""

JS_CONTENT = """
document.addEventListener('DOMContentLoaded', () => {

    // Setup Option Clicks
    const options = document.querySelectorAll('.option-item');
    options.forEach(opt => {
        opt.addEventListener('click', handleOptionClick);
    });

    // Setup Reveal Buttons (Manual override)
    const revealBtns = document.querySelectorAll('.reveal-btn');
    revealBtns.forEach(btn => {
        btn.addEventListener('click', (e) => {
            const card = e.target.closest('.question-card');
            showAnswer(card);
            e.target.style.display = 'none'; // Hide button after reveal
        });
    });
});

function handleOptionClick(e) {
    const option = e.currentTarget;
    const card = option.closest('.question-card');

    // Prevent multiple clicks
    if (card.dataset.answered === "true") return;

    card.dataset.answered = "true";

    // Disable all options in this card
    const allOptions = card.querySelectorAll('.option-item');
    allOptions.forEach(o => o.classList.add('disabled'));

    const selectedValue = option.dataset.option;
    const correctValue = card.dataset.correct;

    if (selectedValue === correctValue) {
        // CORRECT
        option.classList.add('correct');
        // Confetti could go here
    } else {
        // WRONG
        option.classList.add('wrong');

        // Highlight the correct one
        const correctOption = card.querySelector(`.option-item[data-option="${correctValue}"]`);
        if(correctOption) correctOption.classList.add('correct');
    }

    // Auto Reveal Explanation
    showAnswer(card);

    // Hide manual reveal button if it exists
    const btn = card.querySelector('.reveal-btn');
    if(btn) btn.style.display = 'none';
}

function showAnswer(card) {
    const content = card.querySelector('.answer-content');
    if (!content.classList.contains('visible')) {
        content.classList.add('visible');
    }
}
"""

def parse_image_list():
    """Parses image_list.txt to map Pages to Image Filenames."""
    page_map = {}
    if not os.path.exists(IMAGE_LIST_FILE):
        return page_map

    # Blacklist known header/logo dimensions (Width x Height)
    # 638x466 is the ESB Logo
    BLACKLIST_DIMS = {
        (638, 466),
        (1, 1)
    }

    with open(IMAGE_LIST_FILE, 'r') as f:
        for line in f:
            # Format: page num type width height ...
            match = re.search(r'^\s*(\d+)\s+(\d+)\s+\w+\s+(\d+)\s+(\d+)', line)
            if match:
                page_num = str(match.group(1)) # Convert to string to match question parsed page
                img_idx = int(match.group(2))
                width = int(match.group(3))
                height = int(match.group(4))

                # Filter Blacklisted Dimensions
                if (width, height) in BLACKLIST_DIMS:
                    continue

                # Filter small images (icons, noise) - Relaxed threshold slightly for formulas
                if width > 30 and height > 30:
                    filename = f"img-{img_idx:03d}.png" # Default pdfimages format
                    if page_num not in page_map:
                        page_map[page_num] = []
                    page_map[page_num].append(filename)

    return page_map

def parse_txt_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # Split by separator lines using regex for robustness
    raw_blocks = re.split(r'-{10,}', content)
    questions = []

    for block in raw_blocks:
        block = block.strip()
        if not block or "Q.No" not in block:
            continue

        q_data = {}
        try:
            # Extract Page (Metadata we added)
            # Format: "Page: X" at the start
            page_match = re.search(r'Page:\s*(\d+)', block)
            q_data['page'] = page_match.group(1) if page_match else "Unknown"

            # Extract Q.No
            q_no_match = re.search(r'Q\.No:\s*(\d+)', block)
            q_data['number'] = q_no_match.group(1) if q_no_match else "?"

            # Extract ID
            id_match = re.search(r'\n(\d{6,10})', block)
            q_data['id'] = id_match.group(1) if id_match else ""

            # Extract Correct Ans
            ans_match = re.search(r'Correct Ans\s*:\s*([A-D])', block)
            q_data['correct_ans'] = ans_match.group(1) if ans_match else "?"

            # Extract Lines
            lines = [l.strip() for l in block.splitlines() if l.strip()]

            # Find Option Start
            opt_a_idx = -1
            found_ans_line = -1

            for i, line in enumerate(lines):
                if line == 'A' and opt_a_idx == -1: # First 'A'
                    opt_a_idx = i
                if "Correct Ans" in line:
                    found_ans_line = i

            if opt_a_idx != -1:
                # Slicing approach with strict noise filtering
                start_text_idx = 0
                for idx, line in enumerate(lines[:opt_a_idx]):
                     # Skip Header Lines
                     if (line.startswith("Page:") or
                         line.startswith("Q.No") or
                         line.startswith("Subject:") or
                         line.startswith("Questions:") or
                         line.startswith("====") or
                         re.match(r'^\d+$', line)): # ID check
                          continue
                     else:
                          # First valid line found
                          start_text_idx = idx
                          break

                # If everything was skipped, we might have an issue, but usually text follows.
                # If start_text_idx > opt_a_idx, it means no text?
                if start_text_idx >= opt_a_idx:
                    # Fallback
                    start_text_idx = 0

                q_text_lines = lines[start_text_idx:opt_a_idx]
                text_content = " ".join(q_text_lines)
                # Clean Page Markers
                text_content = re.sub(r'<<<PAGE:\d+>>>', '', text_content)
                q_data['text'] = text_content

                # Parse Options
                # Structure: A \n Text \n B \n Text ...
                options = {}
                current_opt = None

                # Iterate from A to Correct Ans
                end_idx = found_ans_line if found_ans_line != -1 else len(lines)

                for i in range(opt_a_idx, end_idx):
                    line = lines[i]
                    if line in ['A', 'B', 'C', 'D']:
                        current_opt = line
                        options[current_opt] = ""
                    elif current_opt:
                        options[current_opt] += line + " "

                # Post-process options to handle empty ones (likely images)
                for code in ['A', 'B', 'C', 'D']:
                    if code in options:
                        # Clean markers from options too
                        options[code] = re.sub(r'<<<PAGE:\d+>>>', '', options[code])
                        if not options[code].strip():
                             options[code] = "[Image/Diagram]"
                q_data['options'] = options
            else:
                q_data['text'] = "Error parsing text"
                q_data['options'] = {}

        except Exception as e:
            print(f"Error parsing: {e}")
            continue

        questions.append(q_data)

    return questions

def generate_html_for_file(filepath, questions, page_images):
    filename = os.path.basename(filepath)
    title = filename.replace('.txt', '').replace('_', ' ')

    questions_html = ""
    for q in questions:
        options_html = ""
        correct_ans = q.get('correct_ans', '?')
        correct_text = q.get('options', {}).get(correct_ans, 'Unknown')

        # Build Options
        has_missing_img_tag = False
        for opt_key in ['A', 'B', 'C', 'D']:
            opt_text = q.get('options', {}).get(opt_key, '').strip()

            if not opt_text:
                opt_text = "[Image/Diagram]" # Changed from "Not Available" as we might have it now
                has_missing_img_tag = True

            # DATA-OPTION attribute for JS
            options_html += f'''
            <li class="option-item" data-option="{opt_key}">
                <span class="option-label">{opt_key}</span>
                <span class="option-text">{opt_text}</span>
            </li>
            '''

        # Get Images for this Page
        page_num = q.get('page', 'Unknown')
        images_html = ""

        # If we have missing tags, we definitely want to show images
        # Or if page has images, just show them?
        # Let's show all images from that page for now.
        # CAUTION: This might show images from previous/next questions on same page.
        # But user wants "correct images in correct places". Can't distinguish question vs question image without OCR.
        # Showing all images from the page at bottom of question is a safe bet.

        if page_num in page_images:
             images_html = '<div class="q-images">'
             for img_file in page_images[page_num]:
                  images_html += f'<img src="../images/{img_file}" class="q-image" alt="Question Diagram">'
             images_html += '</div>'


        # Smart Placeholder for Explanation
        explanation = f"The correct answer is <strong>{correct_ans}</strong> because it matches the definition: <em>{correct_text}</em>."

        question_block = f"""
        <div class="question-card" data-correct="{correct_ans}" data-answered="false">
            <div class="q-header">
                <span class="q-number">Question {q['number']}</span>
                <span class="q-id">ID: {q['id']}</span>
                <span class="q-id" style="margin-left: 10px;">Page: {page_num}</span>
            </div>
            <div class="q-text">
                {q.get('text', '')}
            </div>

            {images_html}

            <ul class="options-list">
                {options_html}
            </ul>
            <div class="answer-section">
                <button class="reveal-btn">Show Answer</button>
                <div class="answer-content">
                    <span class="ai-pill">EXPLANATION</span>
                    <span class="correct-ans-label">Correct Answer: {correct_ans}</span>
                    <p class="explanation-text">{explanation}</p>
                </div>
            </div>
        </div>
        """
        questions_html += question_block

    return HTML_TEMPLATE.format(
        title=title,
        question_count=len(questions),
        questions_html=questions_html
    )

def main():
    # Setup dirs
    pages_dir = os.path.join(OUTPUT_DIR, 'pages')
    css_dir = os.path.join(OUTPUT_DIR, 'css')
    js_dir = os.path.join(OUTPUT_DIR, 'js')
    images_dir = os.path.join(OUTPUT_DIR, 'images')

    for d in [OUTPUT_DIR, pages_dir, css_dir, js_dir, images_dir]:
        if not os.path.exists(d):
            os.makedirs(d)

    # Load Image Map
    print("Parsing image list...")
    page_images = parse_image_list()
    print(f"Found images for {len(page_images)} pages.")

    # Copy Images
    # We only copy images that are actually in the map (filtered)
    print("Copying images...")
    count = 0
    if os.path.exists(IMAGE_SOURCE_DIR):
        for page, img_list in page_images.items():
            for img_file in img_list:
                src = os.path.join(IMAGE_SOURCE_DIR, img_file)
                dst = os.path.join(images_dir, img_file)
                if os.path.exists(src):
                    shutil.copy2(src, dst)
                    count += 1
    print(f"Copied {count} images to dist/images/")

    # Write Assets
    with open(os.path.join(css_dir, CSS_FILE), 'w') as f:
        f.write(CSS_CONTENT)

    with open(os.path.join(js_dir, 'main.js'), 'w') as f:
        f.write(JS_CONTENT)

    # Process Files
    input_files = sorted(glob.glob(os.path.join(INPUT_DIR, '*.txt')))[:MAX_FILES]

    links_html = ""

    for filepath in input_files:
        print(f"Processing: {filepath}")
        questions = parse_txt_file(filepath)

        if not questions:
            continue

        filename = os.path.basename(filepath)
        html_param = filename.replace('.txt', '.html')
        page_content = generate_html_for_file(filepath, questions, page_images)

        with open(os.path.join(pages_dir, html_param), 'w') as f:
            f.write(page_content)

        # Add to index
        display_name = filename.replace('.txt', '').replace('_', ' ')
        links_html += f"""
        <a href="pages/{html_param}" class="card-link">
            <h2>{display_name}</h2>
            <p>{len(questions)} Questions</p>
        </a>
        """

    # Generate Index
    index_content = INDEX_TEMPLATE.format(links_html=links_html)
    with open(os.path.join(OUTPUT_DIR, 'index.html'), 'w') as f:
        f.write(index_content)

    print(f"Website generated in {OUTPUT_DIR}/")

if __name__ == '__main__':
    main()
